apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "efa.fms.io/v1alpha1",
          "kind": "EfaDriver",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "ocp-efa-operator",
              "app.kubernetes.io/instance": "ocp",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "efadriver",
              "app.kubernetes.io/part-of": "ocp-efa-operator"
            },
            "name": "ocp"
          },
          "spec": {
            "awsEfaInstallerVer": "1.26.1",
            "kmmNamespace": "openshift-kmm",
            "openShift": true
          }
        },
        {
          "apiVersion": "efa.fms.io/v1alpha1",
          "kind": "GdrdrvDriver",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "ocp-efa-operator",
              "app.kubernetes.io/instance": "ocp",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "gdrdrvdriver",
              "app.kubernetes.io/part-of": "ocp-efa-operator"
            },
            "name": "ocp"
          },
          "spec": {
            "gdrdrvVer": "2.4",
            "kmmNamespace": "openshift-kmm",
            "openShift": true
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-11-21T02:34:41Z"
    operators.operatorframework.io/builder: operator-sdk-v1.28.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: ocp-efa-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: EfaDriver is the Schema for the efadrivers API
      displayName: Efa Driver
      kind: EfaDriver
      name: efadrivers.efa.fms.io
      version: v1alpha1
    - description: Gdrdrv is the Schema for the gdrdrvs API
      displayName: Gdrdrv Driver
      kind: GdrdrvDriver
      name: gdrdrvdrivers.efa.fms.io
      version: v1alpha1
  description: ocp-efa-operator
  displayName: ocp-efa-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - efa.fms.io
          resources:
          - efadrivers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - efa.fms.io
          resources:
          - efadrivers/finalizers
          verbs:
          - update
        - apiGroups:
          - efa.fms.io
          resources:
          - efadrivers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - efa.fms.io
          resources:
          - gdrdrvdrivers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - efa.fms.io
          resources:
          - gdrdrvdrivers/finalizers
          verbs:
          - update
        - apiGroups:
          - efa.fms.io
          resources:
          - gdrdrvdrivers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kmm.sigs.x-k8s.io
          resources:
          - modules
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - watch
        - apiGroups:
          - nfd.openshift.io
          resources:
          - nodefeaturerules
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: ocp-efa-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: ocp-efa-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: ocp-efa-operator
          control-plane: controller-manager
        name: ocp-efa-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: OPERATOR_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: ghcr.io/foundation-model-stack/ocp-efa-operator:v0.0.1
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: ocp-efa-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: ocp-efa-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ocp
  - efa
  - gdr
  links:
  - name: Ocp Efa Operator
    url: https://ocp-efa-operator.domain
  maintainers:
  - email: tyos@jp.ibm.com
    name: Takeshi Yoshimura
  maturity: alpha
  provider:
    name: Foundation Model Stack
  version: 0.0.1
