# permissions for end users to edit gdrdrvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gdrdrv-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocp-efa-operator
    app.kubernetes.io/part-of: ocp-efa-operator
    app.kubernetes.io/managed-by: kustomize
  name: gdrdrv-editor-role
rules:
- apiGroups:
  - efa.fms.io
  resources:
  - gdrdrvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - efa.fms.io
  resources:
  - gdrdrvs/status
  verbs:
  - get
