name: Build and push test images

on:
  push:
    branches:
      - main
    paths:
      - test/Dockerfile.*
  workflow_dispatch:

env:
  VERSION: '0.0.1'
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-push-gdrcopy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/foundation-model-stack/gdrcopy-test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push gdrcopy-test
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:ocp-efa-v${{ env.VERSION }}
          file: ./test/Dockerfile.gdrcopy

  build-push-nccl-tests:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/foundation-model-stack/nccl-tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push nccl-tests
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:ocp-efa-v${{ env.VERSION }}
          file: ./test/Dockerfile.nccl-tests

  build-push-pytorch:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/foundation-model-stack/pytorch
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push pytorch
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:ocp-efa-v${{ env.VERSION }}
          file: ./test/Dockerfile.pytorch